name: test

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install -r requirements-dev.txt
      - name: テスト
        run: pytest -q
      - name: 設定ファイルの検証
        run: python -m src.main --check --dry-run
